chore(CI/CD): verify GH_TOKEN test

diff --git a/.github/workflows/build_and_release.yaml b/.github/workflows/build_and_release.yaml
--- a/.github/workflows/build_and_release.yaml
+++ b/.github/workflows/build_and_release.yaml
@@ -141,34 +141,34 @@ jobs:
 
       - run: npm i -g semantic-release @semantic-release/{git,exec,changelog}
 
-      - name: Verify GH_TOKEN is set
+      - name: Verify GITHUB_TOKEN is set
         run: |
-          if [ -z "$GH_TOKEN" ]; then
-            echo "::error::GH_TOKEN is not set. Please add GH_TOKEN secret to the repository." >&2
+          if [ -z "$GITHUB_TOKEN" ]; then
+            echo "::error::GITHUB_TOKEN is not set. Please add GITHUB_TOKEN secret to the repository." >&2
             exit 1
           fi
         env:
-          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Verify GH_TOKEN validity with GitHub API
+      - name: Verify GITHUB_TOKEN validity with GitHub API
         run: |
-          status=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $GH_TOKEN" https://api.github.com/user)
+          status=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user)
           echo "Token validation status: $status"
           if [ "$status" -ne 200 ]; then
-            echo "::error::GH_TOKEN is invalid or lacks permissions (HTTP $status)"
+            echo "::error::GITHUB_TOKEN is invalid or lacks permissions (HTTP $status)"
             exit 1
           else
-           echo "GH_TOKEN is valid "
+           echo "GITHUB_TOKEN is valid "
           fi
         env:
-           GH_TOKEN: ${{ secrets.GH_TOKEN }}
+           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
       - name: Run semantic-release
         run: semantic-release
         if: ${{ !env.ACT }}
         env:
-          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   deploy:
     name: Deploy to dev CDN
     runs-on: ubuntu-latest
